Add templates
openprocurement/openprocurement.edr.buildout pull request #2
Opened 2017-03-22 13:01 UTC by Krokop

Додав templates, та base.cfg.

2017-03-22 13:12 UTC, Krokop commented
Залежить від https://github.com/openprocurement/openprocurement.integrations.edr/pull/13

2017-03-22 14:05 UTC, Krokop commented
@kroman0 потрібен ревью

2017-03-22 14:38 UTC, kroman0 requested changes

2017-03-22 14:38 UTC, kroman0 commented on templates/openprocurement.integrations.edr.ini
> +{% if 'health_threshold' in options %}health_threshold = ${options['health_threshold']}{% end %}
Рядки 14-19 для проксі не потрібні

2017-03-22 14:38 UTC, kroman0 commented on templates/openprocurement.integrations.edr.ini
> +keys = console${',loggly' if 'loggly' in options else ''}${',journal' if 'journal' in options else ''}
loggly можна забрати

2017-03-22 14:38 UTC, kroman0 commented on base.cfg
> +aws_access_key = ${openprocurement.api.ini:aws_access_key}
Секції openprocurement.api.ini нема

2017-03-22 15:37 UTC, Krokop commented
@kroman0 виправив згідно Ваших зауважень, потрібен ревью

2017-03-22 16:53 UTC, kroman0 commented on base.cfg
> +aws_access_key = ${openprocurement.integrations.edr.ini:aws_access_key}
aws_access_key нема в секції openprocurement.integrations.edr.ini. Так aws_access_key потрібен тільки для logrotate можна залишити ці параметри пустими і наповнювати при деплойменті

2017-03-22 18:07 UTC, Krokop commented on base.cfg
> +aws_access_key = ${openprocurement.integrations.edr.ini:aws_access_key}
Прибрав

2017-03-23 07:37 UTC, Krokop commented
@kroman0 потрібен ревью

2017-03-23 09:44 UTC, kroman0 requested changes

2017-03-23 09:44 UTC, kroman0 commented on base.cfg
> +    server_cookie_middleware
server_cookie_middleware для проксі не потрібен

2017-03-23 09:45 UTC, Krokop commented on base.cfg
> +    server_cookie_middleware
прибрав

2017-03-23 09:51 UTC, kroman0 approved these changes

2017-03-23 09:52 UTC, merged

2017-03-23 09:55 UTC, Krokop commented
@kroman0 buildout можно вважати завершеним, або є ще якісь необхідні файли?

2017-03-23 10:15 UTC, kroman0 commented
Потрібна ще базова конфігурація для пісочниці (preview.cfg) і продуктиву (production.cfg). Також можна винести source.cfg і journal.cfg

2017-03-23 11:26 UTC, Krokop commented
Створив ПР https://github.com/openprocurement/openprocurement.edr.buildout/pull/3, додав все крім source.cfg бо не знайшов прикладу, або опису що там повино бути.

2017-03-23 12:08 UTC, Krokop commented
@kroman0 де можно знайти source.cfg?

2017-03-23 12:19 UTC, kroman0 commented
Наразі source.cfg не потрібно.

2017-03-23 12:21 UTC, kroman0 commented
Приклад https://github.com/openprocurement/openprocurement.bridge.buildout/blob/master/profiles/sources.cfg